const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),{webcrypto}=require('node:crypto');
const src=fs.readFileSync('app.js','utf8'),part=(a,b)=>src.slice(src.indexOf(a),src.indexOf(b));
const sandbox={Float32Array,Math,Number,Object,Set,Error,JSON,Date,structuredClone,crypto:webcrypto,EVENT:{normal:'결과 없음',goal:'골',foulL:'파울 L',foulH:'파울 H',foul:'파울'},HALF:{first:'전반',second:'후반'},TYPE:{normal:'일반투구',penalty:'페널티투구'},TECHNIQUES:['F','C','SB','LB']};vm.createContext(sandbox);
vm.runInContext(part('function lane(', 'try{const saved=')+part('function heatField(', 'function renderReport('),sandbox);
const rect={left:100,top:20,width:430,height:250};
assert.equal(sandbox.canvasPoint(135,50,rect).x,0);assert.equal(sandbox.canvasPoint(495,230,rect).y,90);assert.equal(sandbox.canvasPoint(110,25,rect),null);assert.equal(sandbox.canvasPoint(315,140,rect).x,90);assert.equal(sandbox.canvasPoint(315,140,rect).y,45);
for(const [y,n] of [[0,0],[14.9,0],[15,1],[30,2],[45,3],[60,4],[75,5],[90,5]])assert.equal(sandbox.lane(y),n);
assert.equal(sandbox.rotatePoint({x:12,y:165}).x,15);assert.equal(sandbox.rotatePoint({x:12,y:165}).y,12);
const one=sandbox.heatField([{x:90,y:45}]),two=sandbox.heatField([{x:90,y:45},{x:90,y:45}]);assert(Math.abs(two.max-2*one.max)<1e-7);for(let y=0;y<90;y++)for(let x=0;x<180;x++)assert(Math.abs(one.field[y*180+x]-one.field[y*180+179-x])<1e-6);assert.equal(sandbox.heatField([]).max,0);
const roster=()=>Array.from({length:6},(_,i)=>({number:String(i+1),name:'선수'+(i+1),position:i<3?['L','C','R'][i]:'',active:i<3}));
const fixture={schemaVersion:4,registered:true,half:'first',name:'경기',date:'2026-10-05',teams:{A:{name:'A',players:roster()},B:{name:'B',players:roster()}},records:[{id:'a',kind:'throw',half:'first',throwType:'normal',team:'A',player:'1',result:'normal',recordedAt:'2026-10-05T00:00:00Z',start:{x:12,y:75},release:{x:18,y:74},target:{x:180,y:15}}]};assert.equal(sandbox.validate(fixture),fixture);
for(const mutate of [m=>m.records[0].target.y=90.1,m=>m.records[0].start=null,m=>m.records[0].result='constructor',m=>m.records[0].half='third',m=>m.teams.A.players[1].number='01',m=>m.teams.A.players[1].position='L',m=>m.teams.A.players[3].active=true,m=>m.records[0].throwType='other']){const bad=structuredClone(fixture);mutate(bad);assert.throws(()=>sandbox.validate(bad));}
for(const team of ['A','B'])for(const half of ['first','second']){const left=(team==='A')===(half==='first'),r={...fixture.records[0],team,half,start:{x:left?10:170,y:12},release:{x:left?20:160,y:18},target:{x:left?170:10,y:75}},normalized=sandbox.normalizeThrow(r);assert.equal(normalized.start.x,10);assert.equal(normalized.release.x,20);assert.equal(normalized.target.x,170);assert.equal(normalized.target.y,75);assert.equal(r.start.x,left?10:170);}
const stats=sandbox.zoneStats([0,15,30,45,60,90].map(y=>({target:{x:170,y}})));assert.deepEqual(Array.from(stats.counts),[1,1,1,1,1,1]);assert(Math.abs(stats.percent.reduce((a,b)=>a+b,0)-100)<1e-10);
const prior={schemaVersion:2,name:'기존',date:'2026-10-05',teams:{A:{name:'A',players:['1']},B:{name:'B',players:['2']}},records:[{id:'old',team:'B',player:'2',result:'foul',recordedAt:'2026-10-05T00:00:00Z',release:{x:12,y:165},target:{x:75,y:0}}]};const migrated=sandbox.migrate(prior);assert.equal(migrated.records[0].start,null);assert.equal(migrated.records[0].release.x,15);assert.equal(migrated.records[0].target.y,75);assert.equal(migrated.records[0].half,'first');assert.equal(migrated.registered,false);assert.equal(sandbox.normalizeThrow(migrated.records[0]).target.x,180);
const v3={...structuredClone(fixture),schemaVersion:3};v3.records[0]={...v3.records[0],team:'B'};const converted=sandbox.migrate(v3);assert.equal(converted.records[0].result,'normal');assert.equal(converted.teams.A.players[0].active,false);assert.equal(sandbox.normalizeThrow(converted.records[0]).start.x,168);
Object.assign(sandbox,{match:structuredClone(fixture),lastThrowId:null,start:null,release:null,target:null,editing:null,checkpoint(){},reset(){sandbox.start=sandbox.release=sandbox.target=null;sandbox.editing=null;},renderPlayers(){},populateFilters(){},save(){},render(){},renderDraft(){},notice(){},athleteLabel(){return '선수';},athlete(t,n){return sandbox.match.teams[t].players.find(p=>p.number===n);}});
vm.runInContext(part('function applyRegistration(', 'function download(')+part('function record(){','function lineup('),sandbox);
const next=structuredClone(sandbox.match);next.teams.A.players[0].active=false;next.teams.A.players[3].active=true;next.teams.A.players[3].position='L';assert.equal(sandbox.applyRegistration(next,true),1);let sub=sandbox.match.records[1];assert.equal(sub.kind,'substitution');assert.equal(sub.afterThrow,1);assert.equal(sub.before[0].active,true);assert.equal(sub.after[0].active,false);assert.equal(sub.after[3].active,true);assert.throws(()=>sandbox.applyRegistration(structuredClone(sandbox.match),true));
sandbox.match.half='second';Object.assign(sandbox,{player:{team:'A',player:'4'},throwType:'penalty',start:{x:170,y:12},release:{x:155,y:14},target:{x:5,y:20}});sandbox.record();assert.equal(sandbox.match.records.length,3);const thrown=sandbox.match.records[2];assert.equal(thrown.half,'second');assert.equal(thrown.throwType,'penalty');assert.equal(thrown.result,'normal');sandbox.recordResult('foulH');assert.equal(thrown.result,'foulH');sandbox.recordResult('goal');assert.equal(thrown.result,'goal');sandbox.recordResult('goal');assert.equal(thrown.result,'normal');sandbox.validate(sandbox.match);
let bad=structuredClone(sandbox.match);bad.records[1].afterThrow=2;assert.throws(()=>sandbox.validate(bad));
const filters={halfFilter:{value:''},teamFilter:{value:''},playerFilter:{value:''},courseFilter:{value:''},eventFilter:{value:''}};sandbox.$=id=>filters[id];vm.runInContext(part('function inReportHalf(', 'function heatField('),sandbox);
assert.equal(sandbox.filtered().length,2);filters.halfFilter.value='first';assert.equal(sandbox.filtered().length,1);assert.equal(sandbox.filtered()[0].half,'first');assert.equal(sandbox.inReportHalf(sub),true);filters.halfFilter.value='second';assert.equal(sandbox.filtered().length,1);assert.equal(sandbox.filtered()[0].player,'4');assert.equal(sandbox.filtered()[0].start.x,10);assert.equal(sandbox.inReportHalf(sub),false);filters.playerFilter.value='A:1';assert.equal(sandbox.filtered().length,0);assert.equal(sandbox.filtered(true).length,1);filters.playerFilter.value='';filters.halfFilter.value='';assert.equal(sandbox.filtered(true).length,2);
sandbox.recordResult('goal');for(const code of ['F','C','SB','LB']){sandbox.recordTechnique(code);assert.equal(thrown.technique,code);assert.equal(thrown.result,'goal');}sandbox.recordResult('foulL');assert.equal(thrown.technique,'LB');sandbox.recordTechnique('LB');assert.equal(thrown.technique,null);assert.equal(thrown.result,'foulL');sandbox.recordTechnique('SB');sandbox.start={x:160,y:10};sandbox.recordTechnique('C');assert.equal(thrown.technique,'SB');sandbox.release={x:150,y:20};sandbox.target={x:5,y:30};sandbox.editing=thrown.id;sandbox.record();const updated=sandbox.match.records[2];assert.equal(updated.technique,'SB');assert.equal(updated.result,'foulL');assert.equal(sandbox.match.records.length,3);Object.assign(sandbox,{start:{x:170,y:10},release:{x:150,y:10},target:{x:5,y:30}});sandbox.record();assert.equal(sandbox.match.records[3].technique,null);assert.equal(sandbox.match.records[3].result,'normal');sandbox.validate(JSON.parse(JSON.stringify(sandbox.match)));bad=structuredClone(sandbox.match);bad.records[0].technique='other';assert.throws(()=>sandbox.validate(bad));
console.log('PASS: report half filters; half-time normalization; roster/substitutions; independent post-throw F/C/SB/LB and G/L/H, toggling, editing preservation, new-throw reset, JSON validation; Gaussian density; legacy migration.');
