const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),{webcrypto}=require('node:crypto');
const src=fs.readFileSync('app.js','utf8'),part=(a,b)=>src.slice(src.indexOf(a),src.indexOf(b));
const elements={};const $=id=>elements[id]||=( {value:'',hidden:false} );
const sandbox={Float32Array,Math,Number,Object,Set,Error,JSON,Date,structuredClone,crypto:webcrypto,$,EVENT:{normal:'결과 없음',goal:'골',foulL:'파울 L',foulH:'파울 H',foul:'파울'},HALF:{first:'전반',second:'후반'},TYPE:{normal:'일반투구',penalty:'페널티투구'},TECHNIQUES:['F','C','SB','LB']};vm.createContext(sandbox);
vm.runInContext(part('function lane(', 'try{const saved=')+part('function heatField(', 'function renderReport('),sandbox);
const roster=()=>Array.from({length:6},(_,i)=>({number:String(i+1),name:'',position:i<3?['L','C','R'][i]:'',active:i<3}));
const shot=(id='one')=>({id,kind:'throw',half:'first',throwType:'normal',team:'A',player:'1',result:'normal',technique:null,recordedAt:'2026-10-08T00:00:00Z',start:{x:12,y:78},release:{x:18,y:74},target:{x:180,y:12},techniqueTime:null,resultTime:null,postEvents:[]});
const fixture={schemaVersion:5,appVersion:2,registered:true,half:'first',name:'경기',date:'2026-10-08',teams:{A:{name:'A',players:roster()},B:{name:'B',players:roster()}},records:[shot()]};assert.equal(sandbox.validate(fixture),fixture);
const rect={left:100,top:20,width:430,height:250};assert.equal(sandbox.canvasPoint(135,50,rect).x,0);assert.equal(sandbox.canvasPoint(495,230,rect).y,90);assert.equal(sandbox.canvasPoint(315,140,rect).x,90);assert.equal(sandbox.canvasPoint(110,25,rect,true),null);
for(const [px,py,out,goalSide] of [[250,47,'left','left'],[250,433,'right','left'],[610,47,'right','right'],[610,433,'left','right']]){const x=100+px/2,y=20+py/2;assert.equal(sandbox.canvasPoint(x,y,rect),null);const p=sandbox.canvasPoint(x,y,rect,true);assert.equal(p.out,out);assert.equal(p.goalSide,goalSide);assert.equal(p.x,undefined);assert.equal(p.y,undefined);}
for(const [y,n] of [[0,0],[14.9,0],[15,1],[30,2],[45,3],[60,4],[75,5],[90,5]]){assert.equal(sandbox.lane(y,'right'),n);assert.equal(sandbox.lane(90-y,'left'),n);}
for(const team of ['A','B'])for(const half of ['first','second']){const left=(team==='A')===(half==='first'),r={...shot(),team,half,start:{x:left?10:170,y:left?78:12},release:{x:left?20:160,y:left?72:18},target:{x:left?170:10,y:left?12:78}},normalized=sandbox.normalizeThrow(r);assert.equal(normalized.start.x,10);assert.equal(normalized.start.y,78);assert.equal(normalized.release.y,72);assert.equal(normalized.target.x,170);assert.equal(normalized.target.y,12);assert.equal(sandbox.targetCourse(r),'0');assert.equal(sandbox.targetCourse(normalized),'0');assert.equal(sandbox.pointDescription(r.start,sandbox.attackSide(r)),'1');assert.equal(r.start.y,left?78:12);const out=sandbox.normalizeThrow({...r,target:{out:'right',goalSide:left?'right':'left'}});assert.equal(out.target.out,'right');assert.equal(out.target.goalSide,'right');}
const mixed=[...Array.from({length:6},(_,i)=>({...shot(String(i)),target:{x:180,y:i*15}})),{...shot('L'),target:{out:'left',goalSide:'right'}},{...shot('R'),target:{out:'right',goalSide:'right'}}];const stats=sandbox.zoneStats(mixed);assert.deepEqual(Array.from(stats.counts),[1,1,1,1,1,1]);assert.equal(stats.outs.left,1);assert.equal(stats.outPercent.right,12.5);assert.equal(stats.percent.reduce((a,b)=>a+b,0)+stats.outPercent.left+stats.outPercent.right,100);assert.equal(sandbox.zoneStats([]).outs.right,0);
for(const mutate of [m=>m.records[0].target={out:'right',goalSide:'right',x:180,y:0},m=>m.records[0].start={out:'right',goalSide:'left'},m=>m.records[0].target={out:'other',goalSide:'right'},m=>m.records[0].target.y=90.1,m=>m.records[0].resultTime='3:60',m=>m.records[0].technique='unknown',m=>m.teams.A.players[1].position='L',m=>m.teams.A.players[1].number='01']){const bad=structuredClone(fixture);mutate(bad);assert.throws(()=>sandbox.validate(bad));}
assert.equal(sandbox.parseEventTime('3','7'),'03:07');assert.equal(sandbox.parseEventTime('','12'),'00:12');assert.equal(sandbox.parseEventTime('4',''),'04:00');assert.equal(sandbox.parseEventTime('',''),null);for(const [m,s] of [['-1','0'],['1','60'],['1.2','0'],['1000','0']])assert.throws(()=>sandbox.parseEventTime(m,s));
const one=sandbox.heatField([{x:90,y:45}]),two=sandbox.heatField([{x:90,y:45},{x:90,y:45}]);assert(Math.abs(two.max-2*one.max)<1e-7);assert.equal(sandbox.heatField([]).max,0);
const prior=structuredClone(fixture);prior.schemaVersion=4;delete prior.appVersion;prior.records[0].technique='LB';prior.records[0].result='foulH';const oldBytes=JSON.stringify(prior),converted=sandbox.migrate(prior);assert.equal(JSON.stringify(prior),oldBytes);assert.equal(converted.schemaVersion,5);assert.equal(converted.registered,true);assert.equal(converted.records[0].technique,'LB');assert.equal(converted.records[0].result,'foulH');assert.equal(converted.records[0].target.y,12);assert.equal(converted.records[0].resultTime,null);
const oldV2={schemaVersion:2,name:'기존',date:'2026-10-05',teams:{A:{name:'A',players:['1']},B:{name:'B',players:['2']}},records:[{id:'old',team:'B',player:'2',result:'normal',recordedAt:'2026-10-05T00:00:00Z',release:{x:12,y:165},target:{x:75,y:0}}]};const migrated=sandbox.migrate(oldV2);assert.equal(migrated.records[0].start,null);assert.equal(migrated.records[0].release.x,15);assert.equal(sandbox.normalizeThrow(migrated.records[0]).target.y,75);assert.equal(migrated.registered,false);
Object.assign(sandbox,{match:structuredClone(fixture),lastThrowId:null,start:null,release:null,target:null,editing:null,checkpoint(){},reset(){sandbox.start=sandbox.release=sandbox.target=null;sandbox.editing=null;},renderPlayers(){},populateFilters(){},save(){},render(){},renderDraft(){},notice(){},athleteLabel(){return '선수';},athlete(t,n){return sandbox.match.teams[t].players.find(p=>p.number===n);}});
vm.runInContext(part('function applyRegistration(', 'function download(')+part('function record(){','function lineup(')+part('function inReportHalf(', 'function heatField('),sandbox);
let next=structuredClone(sandbox.match);next.teams.A.players[0].position='R';next.teams.A.players[2].position='L';assert.equal(sandbox.applyRegistration(next,true,'03:15'),1);assert.equal(sandbox.match.records[1].kind,'positionChange');assert.equal(sandbox.match.records[1].eventTime,'03:15');assert.equal(sandbox.match.records[1].afterThrow,1);
next=structuredClone(sandbox.match);next.teams.A.players[0].active=false;next.teams.A.players[3].active=true;next.teams.A.players[3].position='R';next.teams.A.players[1].position='L';next.teams.A.players[2].position='C';assert.equal(sandbox.applyRegistration(next,true,'04:20'),2);assert.equal(sandbox.match.records[2].kind,'substitution');assert.equal(sandbox.match.records[3].kind,'positionChange');assert.equal(sandbox.match.records[2].afterThrow,1);assert.equal(sandbox.match.records[3].afterThrow,1);
next=structuredClone(sandbox.match);next.teams.A.players[1].name='이름 보완';assert.equal(sandbox.applyRegistration(next,false),0);assert.equal(sandbox.match.records.length,4);assert.throws(()=>sandbox.applyRegistration(structuredClone(sandbox.match),true));
sandbox.match.half='second';Object.assign(sandbox,{player:{team:'A',player:'4'},throwType:'penalty',start:{x:170,y:12},release:{x:155,y:14},target:{out:'left',goalSide:'left'}});sandbox.record();let thrown=sandbox.match.records[4];assert.equal(thrown.half,'second');assert.equal(thrown.target.x,undefined);assert.equal(thrown.technique,null);$('techniqueTimeMinute').value='5';$('techniqueTimeSecond').value='9';sandbox.recordTechnique('SB');$('resultTimeMinute').value='5';$('resultTimeSecond').value='11';sandbox.recordResult('foulL');assert.equal(thrown.techniqueTime,'05:09');assert.equal(thrown.resultTime,'05:11');assert.equal(thrown.postEvents.length,2);$('resultTimeSecond').value='12';sandbox.updatePostTime('result');assert.equal(thrown.resultTime,'05:12');assert.equal(thrown.postEvents.length,3);$('resultTimeSecond').value='60';sandbox.recordResult('goal');assert.equal(thrown.result,'foulL');$('resultTimeSecond').value='12';
Object.assign(sandbox,{start:{x:170,y:15},release:{x:150,y:20},target:{out:'right',goalSide:'left'},editing:thrown.id});sandbox.record();thrown=sandbox.match.records[4];assert.equal(thrown.techniqueTime,'05:09');assert.equal(thrown.resultTime,'05:12');assert.equal(thrown.postEvents.length,3);sandbox.validate(JSON.parse(JSON.stringify(sandbox.match)));
for(const id of ['halfFilter','teamFilter','playerFilter','courseFilter','techniqueFilter','eventFilter'])$(id).value='';assert.equal(sandbox.filtered().length,2);$('courseFilter').value='out-right';assert.equal(sandbox.filtered(true).length,1);$('techniqueFilter').value='SB';$('halfFilter').value='second';assert.equal(sandbox.filtered().length,1);$('playerFilter').value='A:1';assert.equal(sandbox.filtered().length,0);assert.equal(sandbox.filtered(true).length,1);$('halfFilter').value='first';assert.equal(sandbox.filtered(true).length,0);
// Both legacy backups and the new storage namespace must remain available.
assert(src.includes("const STORAGE = 'goalball-live-v5'"));assert(src.includes("localStorage.getItem('goalball-live-v4')"));assert(fs.existsSync('v1.html'));assert.equal(fs.readFileSync('v1.html','utf8').includes("const STORAGE = 'goalball-live-v4'"),true);assert(fs.existsSync('GOALBALL_LIVE-v1-backup.zip'));
console.log('PASS v2: unnamed roster; position vs substitution and mixed changes; manual event times/history/editing; goal-relative six zones and 180-degree reports; symbolic outs without distances; out frequency/filters; v1 migration and independent storage.');
